### ISSUE TITLE
Clarifying solution branch access

### ISSUE THREAD

**Issue by hoffm386** [learn-co-curriculum/dsc-structure-of-this-course#5]
Highlight the information about the solution branch more clearly. Maybe use bold for the amount of time they should spend. Maybe add objectives/agenda at the top to help draw attention to the fact that this covers how to find lab solutions

**Comment by bpurdy-ds** [comment]
Missing an index file, the README was still in terms of ID not SC, and the Canvas page was not connected to this. Verbiage was updated as well. Commit closed: https://github.com/learn-co-curriculum/dsc-structure-of-this-course/issues/5#issue-991427054
